Back-End/phenom/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path , include
from django.views.generic.base import TemplateView
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register , name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html') , name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='phenom_app/home.html') , name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password-reset/password-reset.html',
        subject_template_name='users/password-reset/password_reset_subject.txt',
        html_email_template_name='users/password-reset/password_reset_email.html'
    ), name='password-reset') ,

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password-reset/password-reset.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),


    path('profile/change-pass/',  user_views.CustomPasswordChangeView.as_view(), name='change-pass'),
    #path('logout/' , name='logout'),
    path('activate/<uidb64>/<token>/',user_views.activate, name='activate'),
    path('', include('phenom_app.urls')),
    
    path("payment-request/<int:plan_id>/", user_views.send_request, name='payment-request'),
    path("unsuccessful-payment/", TemplateView.as_view(template_name='users/payment/unsuccessful-payment.html'), name='unsuccessful-payment'),
    path("successful-payment/", user_views.successful_payment , name='successful-payment'),
    path("verify/", user_views.verify , name='verify'),
    path("validate-license/", user_views.validateLicense , name='validate'),
    path('dashboard/', user_views.dashboard ,name='dashboard'),
    path('purchased-licenses/', user_views.purchased_licenses ,name='purchased-licenses'),
    path('profile/', user_views.profile ,name='profile'),
    path('buy-license/', user_views.buy_license ,name='buy-license'),
    path('mark-as-read/', user_views.mark_as_read ,name='mark_as_read'),

]

Back-End/phenom_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home , name='home'),
    path('doc/', views.doc, name='doc'),
    path('tech-info/', views.tech_info, name='tech-info'),
    path('contact-us/', views.contact_us, name="contact-us"),
    path('download-phenom/', views.download_view ,name='download'),
]

Back-End/phenom_app/models.py
from django.db import models

# Create your models here.

Back-End/phenom_app/forms.py
from django import forms

class ContactUs(forms.Form):
    name = forms.CharField(label='name', max_length=100, required=True)
    email = forms.EmailField(label='email', max_length=150, required=True)
    phone = forms.CharField(label='phone', max_length=15, required=False)
    site = forms.CharField(label='site', max_length=30, required=False)
    message = forms.CharField(label='message', max_length=300, required=True)

Back-End/phenom_app/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import ContactUs
from django.utils.translation import activate
from django.core import mail

activate('fa')

def home(request) :
    return render(request , 'phenom_app/home.html')

def doc(request):
    return render(request , 'phenom_app/doc-page.html')

def tech_info(request):
    return render(request , 'phenom_app/tech-info.html')

def download_view(request):
    return render(request , 'phenom_app/downloadpage.html')

def contact_us(request):

    if request.method == 'POST':

        form = ContactUs(request.POST)

        if form.is_valid():
            
            _email = form.cleaned_data.get('email')
            _message = form.cleaned_data.get('message')
            _name = form.cleaned_data.get('name')
            _site = form.cleaned_data.get('site')
            _phone = form.cleaned_data.get('phone')
            
            whole_data  = f"email: {_email}\n"
            whole_data += f"name: {_name}\n"
            whole_data += f"message: {_message}\n"
            whole_data += f"web site: {_site}\n"
            whole_data += f"phone number: {_phone}\n"
            from_email='app.phenom@gmail.com'
            
            mail.send_mail("Contact Us Stuff", whole_data, from_email, [from_email])
            
            # messages.success(request, 'پیام با موفقیت ارسال شد :)')
            return render(request, 'phenom_app/message-recorded.html')
            # return redirect("contact-us")

    else:
        form = ContactUs()

    return render(request, 'phenom_app/contact-us.html', {'form': form})

Back-End/phenom_app/templates/phenom_app/contact-us.html
{% load static %}

<!doctype html>
<html lang="en">
<head>


	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="{% static 'phenom_app/contact-us/assets/img/favicon.ico' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Phenom</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

      <link rel="stylesheet" href="{% static 'phenom_app/contact-us/assets/css/style.css' %}">

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'phenom_app/contact-us/assets/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!--  Light Bootstrap Table core CSS    -->
    {% comment %} <link href="assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/> {% endcomment %}

    <style> 
        @font-face {
           font-family: myFirstFont;
           src: url("{% static 'phenom_app/fonts/IRANSansWeb.woff' %}");
        }
        
        * {
           font-family: myFirstFont !important;
        }
    </style>
    


</head>
<body style="background-color:#21aae1">


    
    
    
    <div class="container">  
    <form id="contact" method="post" dir="rtl">
    {% csrf_token %}
        <img src="{% static 'phenom_app/contact-us/assets/phnm.jpg' %}" alt="Trulli" width="320" height="120">
        <h4 style="font-size: 1.3em;">مشکل یا پیشنهاد خود را برای ما بنویسید</h4>
        <fieldset>
        <input placeholder="نام و نام خانوادگی" type="text" tabindex="1" required autofocus name="name" id="id_name" value="{{ form.name.value|default_if_none:'' }}">
        <small style="color:Red;" dir="rtl">{{ form.name.errors }}</small>
        </fieldset>
        <fieldset>
        <input placeholder="آدرس ایمیل" type="email" tabindex="2" required name="email" id="id_email" value="{{ form.email.value|default_if_none:''}}">
        <small style="color:Red;" dir="rtl">{{ form.email.errors }}</small>
        </fieldset>
        <fieldset>
        <input placeholder="شماره تلفن (اختیاری)" type="tel" tabindex="3" name="phone" id="id_phone" value="{{ form.phone.value|default_if_none:'' }}">
        <small style="color:Red;" dir="rtl">{{ form.phone.errors }}</small>
        </fieldset>
        <fieldset>
        <input placeholder="وبسایت (اختیاری)" type="url" tabindex="4" name="site" id="id_site" value="{{ form.site.value|default_if_none:'' }}">
        <small style="color:Red;" dir="rtl">{{ form.site.errors }}</small>
        </fieldset>
        <fieldset>
        <textarea placeholder="پیام خود را اینجا بنویسید" tabindex="5" required name="message" id="id_message" value="{{ form.message.value|default_if_none:'' }}"></textarea>
        <small style="color:Red;" dir="rtl">{{ form.message.errors }}</small>
        </fieldset>
        <fieldset>
        <button name="submit" type="submit" id="id_submit" data-submit="...Sending">ارسال</button>
        </fieldset>
        {% if messages %}
        {% for message in messages %}
            <div id="alertbox" class="my-3 alert alert-success"><strong>{{ message }}ا</strong></div>
        {% endfor %}
    {% endif %}
    </form>
     
    </div>

</body>


</html>

Back-End/phenom_app/templates/phenom_app/doc-page.html
<!doctype html>
{% load static %}
<html lang="en">
<head>


	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="{% static 'phenom_app/doc-page/assets/img/favicon.ico' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Phenom</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

      <!-- <link rel="stylesheet" href="{% static 'phenom_app/doc-page/assets/css/style.css' %}"> -->

      <link rel="stylesheet" href="{% static 'phenom_app/tech-info/assets/css/style.css' %} ">
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'phenom_app/doc-page/assets/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'phenom_app/doc-page/assets/css/light-bootstrap-dashboard.css?v=1.4.0' %}" rel="stylesheet"/>

    <style> 
      @font-face {
         font-family: myFirstFont;
         src: url("{% static 'phenom_app/fonts/IRANSansWeb.woff' %}");
      }
      
      * {
         font-family: myFirstFont;
      }
  </style>


</head>
<body style="background-color:#21aae1">


    
    
   
  <div class="container" style="background-color:#21aae1">  
    <form id="contact" action="" method="post" dir="rtl">
       
      
    
       
      <fieldset>
        <div style="margin-left: 10px; margin-right: 10px; font-size:30px;">
  
          <h1 style="margin-bottom:60px; text-align: center;">
            اسناد نرم افزار
          </h1>
          <p tabindex="5" required style="font-size: 20px;">
          برای هیچ کدام از توزیع های سیستم عامل لینوکس یک دستیار صوتی هوشمند به
          صورت اختصاصی ساخته نشده است
           <br>
             در حالیکه سیستم عامل های اندروید، ویندوز و مک دستیار هوشمند اختصاصی خود را دارند
            <br>
            وضعیت موجود ما را برآن داشت تا دستیار صوتی اختصاصی جدیدی برای توزیع های لینوکس ایجاد کنیم
            <br>
            
            <br>
            امکانات این اپلیکیشن :
            <br>
            فنوم می‌تواند دستورات را به صورت دریافت کند
            <br>
             فنوم‌می‌تواند‌ صوت‌ را‌ به‌ متن‌ و‌ متن‌ را‌ به‌ زبان‌ دیگری‌ ترجمه‌ یا‌ بازگردانی‌ کند‌ و‌ بخواند
             <br>
              فنوم می‌تواند کارها و وظایف مختلف روزمره ی کامپیوتر از قبیل خاموش و روشن کردن و باز و بستن یک
               برنامه را انجام دهد، و همچنین پکیج های مورد نیاز کاربر را نصب کند.
             <br>
             فنوم‌ می‌تواند‌ ورودی‌ مورد‌ نظر‌ را‌ در‌ موتور‌ جستجوی‌ تعیین‌شده‌ جستجو‌ کند‌ و‌ آب‌ و‌ هوا،‌اطلاعات
             سیستمی‌ و‌...‌ را‌ گزارش‌ دهد.
             <br>
             فنوم می‌تواند برنامه‌ریزی روزانه را دریافت و یادآوری کند و در برنامه‌ریزی روزانه کمک کند.
             
               <br>
               
               <br>
               مشتریان یا کاربران اپلیکیشن :
               <br>
               کاربران سیستم عامل لینوکس
               <br>
               معلولین
               <br>
               شرکت ها یا مراکز آموزشی
               <br>
               مشتریان اینترنت اشیا
               

          
          </p>
           
          
        </div>
        
      </fieldset>
  
  
    </form>
  </div>
  
  
  </body>


</html>

Back-End/phenom_app/templates/phenom_app/downloadpage.html
{% load static %}
<html>
    <head>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <title>download phenom</title>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style> 
        @font-face {
           font-family: myFirstFont;
           src: url("{% static 'phenom_app/fonts/IRANSansWeb.woff' %}");
        }
        
        * {
           font-family: myFirstFont;
        }
    </style>
    </head>
      
      <body class="bg-secondary">
        <div class="container card mt-5 ">
            <div class="row align-self-center">
                <div class="border-dark text-center">
                    <div class="text-center mt-5">
                        <h1>
                            برای دانلود نسخه 1 نرم افزار بر روی دکمه زیر کلیک کنید
                        </h1>
                    </div>
                    <div class="text-info my-5">
                        <h4>
                            : این نسخه در فاز آزمایشی قرار دارد که میتوانید آن را از طریق لینک زیر دریافت کنید
                        </h4>
                    </div>
                    <div class="btn btn-warning my-5" dir="rtl">
                        <h3>دانلود phenom v1.0</h3>
                    </div>
                </div>
            </div>
        </div>
      </body>
  
  </html>
  
  

Back-End/phenom_app/templates/phenom_app/message-recorded.html
{% load static %}
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  </head>
    <style>
      @font-face {
          font-family: myFirstFont;
          src: url("{% static 'phenom_app/fonts/IRANSansWeb.woff' %}");
      }
      
      * {
          font-family: myFirstFont !important;
      }
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>

    <body>
      <div class="card">
        <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
            <i class="checkmark">✓</i>
        </div>
            <h1 dir="rtl">ممنون !</h1> 
            <p>نظر شما ثبت شد<br/>تیم پشتیبانی فنوم بزودی با شما در تماس خواهند بود</p>
            <!-- <p class="my-1">____________________</p> -->
            <div style="margin-top: 10px;">
                <a class="btn btn-success btn-primary btn-lg" href="{% url 'home' %}">
                    بازگشت به صفحه اصلی
                </a>
            </div>
        </div>
      
    </body>

</html>

Back-End/phenom_app/templates/phenom_app/tech-info.html
<!doctype html>
{% load static %}
<html lang="en">
<head>


	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="{% static 'phenom_app/tech-info/assets/img/favicon.ico' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Phenom</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

      <link rel="stylesheet" href="{% static 'phenom_app/tech-info/assets/css/style.css' %} ">

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'phenom_app/tech-info/assets/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'phenom_app/tech-info/assets/css/light-bootstrap-dashboard.css?v=1.4.0' %}" rel="stylesheet"/>


    <style> 
      @font-face {
         font-family: myFirstFont;
         src: url("{% static 'phenom_app/fonts/IRANSansWeb.woff' %}");
      }
      
      * {
         font-family: myFirstFont;
      }
  </style>
  

</head>
<body style="background-color:#21aae1">


<div class="container" style="background-color:#21aae1">  
  <form id="contact" action="" method="post" dir="rtl">

     
    <fieldset>
      <div style="margin-left: 10px; margin-right: 10px; font-size:30px;">

        <h1 style="margin-bottom:60px; text-align: center;">
          اطلاعات فنی نرم افزار
        </h1>
        <p tabindex="5" required style="font-size: 20px;"> به‌طور کلی پروژه‌ی فنوم به دو زیر بخش تقسیم می‌شود؛ نرم‌افزار دسکتاپ، و سایت فنوم. که سایت فنوم (همچون هر وب‌سایتی دیگر!) به دو زیر بخش فرانت‌اند و بک‌اند تقسیم می‌شود
        <br>
        در ادامه اشاره‌ای به تکنولوژی‌های استفاده شده در هر زیر بخش خواهیم کرد:
        <br>
        الف: نرم‌افزار دسکتاپ
        <br>
         فنوم یک دستیار هوشمند صوتی است که میتواند به کارهای روزمره شما با لینوکس سرعت ببخشد
         <br>
         و خیلی از کارهای تکراری و روزمره شما را به صورت خودکار انجام دهد تا در وقت شما صرفه جویی شود
         <br>
         تیم فنوم با استفاده از یادگیری ماشین و زبان پایتون این قابلیت را به دستیار صوتی شما داده است که مطالب جدید بیاموزد
         <br>
         بنابراین هر مقدار که جامعه فنوم بزرگتر شود این دستیار صوتی دارای عملکرد بهتری خواهد شد
         <br>
           <br>
         ب: سایت فنوم
         <br>
         قسمت فرانت‌اند وب‌سایت فنوم را با استفاده از HTML , CSS , BootStrap و javascript طراحی کرده ایم که به دو بخش HomePage  و UserPanel  تقسیم میشود.

         <br>
         در صفحه HomePage سایت به معرفی خدمات و ویژگی های محصول پرداخته ایم همچنین اعضای گروه فنوم را به همراه وظایف آنها در گروه معرفی کرده ایم .
         <br>
          در صفحه ذکر شده امکان رفتن به صفحات دانلود نرم افزار، ثبت پیشنهادات و انتقادات، اسناد فنی و تحلیلی سایت و همچنین شبکه های اجتماعی محصول و اعضای تیم وجود دارد.
          <br>
          در قسمت UserPanel نیز کاربر امکان مشاهده اشتراک فعلی، اشتراک های خریداری شده، اشتراک های موجود و تغییر اطلاعات کاربری خود را دارد.
          <br>
          همچنین امکانی قرار داده شده که کاربر بتواند notification  های ارسالی از سمت سرور را مشاهده کند.

          <br>
           بک‌اند وب‌سایت فنوم با استفاده از زبان پایتون و فریم‌ورک Django نوشته شده است، و پایگاه‌ داده‌ی استفاده‌شده SQLite است.
          <br>

        </p>

      </div>

    </fieldset>
    <div style="text-align:center;">
            <h3>ER Diagram</h3>
          <img src="{% static 'phenom_app/tech-info/assets/ERD.png' %}" width="720" height="600" >
     </div>

  </form>


</div>


</body>


</html>